### ISSUE TITLE
Optional wider range of base unit exponents?

### ISSUE THREAD

**Issue by SimonHeybrock** [LLNL/units#127]
Hi!

For our application we are a bit worried about the (limited) range of supported exponents. There are two aspects, I think:
1. Ability to detect over- or underflow in operation such as `operator*` or `operator/`. When in use by a wrapping Python library it is in practice difficult to ensure that the allowed range of base unit powers is not exceeded. I could not find a way to detect this?
2. Extending the range of allowed powers, by increasing the width of `unit_data`.
   - Would alleviate the issues related to 1.)
   - Would fix some actual limitations. For example, `counts` has a maximum exponent of `+1`, but we routinely require `+2`, e.g., since the unit of the variance (square of standard-deviation) is `counts**2`.

Obviously 2.) is in conflict with design requirements regarding size, so the question is whether making this configurable at compile time would be acceptable?

I gave this a try in my fork (doubling the size of `unit_data` and the bitfields inside), and it seems to work with very few changes (apart from some failing unit test with custom units). For our application the unit is typically attached to a large array, so the extra couple of bytes are not an issue.

Would you consider accepting such a change where, e.g., a `cmake` flag could enable a wider `unit_data` type with a greater exponent range? If so, I can clean up my branch and open a PR for further discussion.

**Comment by phlptp** [comment]
for 1, it would need to be done in C++11 constexpr expression which could be difficult, and actually the wrapping behavior is utilized in a few cases so not sure I would want that checking in general.    Something like a checked_multiply might be appropriate that wouldn't operate in constexpr and does any required checks might be appropriate.  

As far as increasing the range the space requirements for many of our applications mean we didn't really consider that.    I think most of the code would work fine though,  Obviously have to change the unit_data class and the static asserts since they would all fail, but most other stuff should be the same.    It would create some gaps in the data structures but if space isn't much of an issue that shouldn't be too big of deal.    As far as a PR, I would want to be careful with it but not completely opposed.  We would need to add one of the CI builds that actually used the change to make sure all the tests still passed.

**Comment by SimonHeybrock** [comment]
> Something like a checked_multiply might be appropriate that wouldn't operate in constexpr and does any required checks might be appropriate.

That sounds like a good suggestion, I'll look into it.

> I think most of the code would work fine though, Obviously have to change the unit_data class and the static asserts since they would all fail, but most other stuff should be the same.

It does, I had experimented with this change yesterday and didn't encounter real issues so far. But you make a very good point about the CI and test coverage.

**Comment by SimonHeybrock** [comment]
Fixed in #142.
