### ISSUE TITLE
Surprising parse results with `.` and `-`

### ISSUE THREAD

**Issue by jl-wynen** [LLNL/units#246]
`unit_from_string` produces some unexpected results when parsing strings with periods or dashes. E.g. all of the following are equivalent to `"m*s"`:
```c++
"m.s"
"m. s"
"m.s."
"m. s."
"m- s"
```
But spacing matters and `"m-s"` is parsed as milliseconds.

This came up for us with `"a.u."` which was intended as 'arbitrary units' but was parsed as `"1.66054e-25*m**2*kg**1"`.

Is it a design choice to interpret `.` as `*` and drop `-` when there are no numbers?

**Comment by phlptp** [comment]
Yeah, it is a balancing job between a number of different unit conventions.  There are a few programs which specify that `.` is a multiplier,  other programs or conventions where a space is a multiplier.  And in a linguistic sense `-` is a connector that bridges two parts of a word or a prefix or modifier.    So I am sure there are a few cases where the complex conglomeration of those conventions make the interpretation a bit odd.   I suppose some additional consideration of situations that end in a `.` might be warranted as that would indicate the `.` being used as an abbreviation rather than as a multiplier.    If there are specific unit strings that get interpreted incorrectly there are a couple different ways I put in to interpret them  and bypass most of the other  logic that tries to figure out some sort of meaning from strings and break it into individual components.

**Comment by phlptp** [comment]
Playing around with this and how to interpret '.'    This is what I have currently

```c++
EXPECT_EQ(precise::m * precise::s, unit_from_string("m.s"));
    EXPECT_EQ(precise::m * precise::s, unit_from_string("m. s"));
    EXPECT_EQ(precise::milli * precise::s, unit_from_string("m. s."));
    EXPECT_EQ(precise::m * precise::s, unit_from_string("m- s"));
    EXPECT_EQ(precise::milli * precise::s, unit_from_string("m-s"));
    EXPECT_EQ(precise::milli * precise::s, unit_from_string("m.s."));
```
`a.u.` in this context would be interpreted as astronomical unit instead of a*u

basic rule would be any non numerically sensible `.` would be interpreted as an abbreviation if at the end or followed by a space, otherwise it could be considered a multiplier.  And it must be consistent for the whole unit string.  I.e if one `.` shows as abbreviation all will.  

If any show as an abbreviation they essentially get removed

**Comment by SimonHeybrock** [comment]
> And it must be consistent for the whole unit string. I.e if one . shows as abbreviation all will.

:+1: nice approach, that makes sense!

What about the recommended (by a number of Journals) abbreviation for "arbitrary units": `arb. unit`? Does this parse correctly with the suggested change?

**Comment by phlptp** [comment]
I went through and looked at a few other units that end in "unit" and added some additional string associated with them and a few modifiers as well so "arb. unit" as a well as a few other descriptions of that will get interpreted as arbitrary unit
