### ISSUE TITLE
"Stress testing" units' string parsing

### ISSUE THREAD

**Issue by SimonHeybrock** [LLNL/units#293]
We had some "fun" with the OpenAI API (using `gpt-3.5-turbo`) trying to find cases where the unit parser is not working so well. Here is the result for now.

This is not necessarily a request to fix all these, but it opens some questions. My main worry is the high false-positive rate (positive in the sense of "parsed" without returning an error). From my point of view, returning an error would be preferable to returning some very wrong unit combination, even if it comes at the cost of rejecting more user input.

|Input| Output| Comment|
|---|---|---|
| gramm | 6.47989100000000217e-23g*m | this would be a typo, or German spelling
| kilogramm | 6.47989100000000188e-20g*m | ?
| cars/hour/meter^2 | 1/h | ?
| cm+cm | cm^2 | ?
| fps | ft/s | not sure if this is the most common interpretation? Isn't frames per second more common?
| Metres | Unsupported unit. | Not so important, but most other variations seem to work
| degrees C | `0.0174532925199432955s*A*rad` | would expect an error instead of bad parsing
| inchy | 4830819306288062m^3/[c] | would expect an error instead of bad parsing
| fln_oz | 9.7132811577355196e-08g*cd/m^2 | would expect an error instead of bad parsing
| kM | kmol/L | correct, but may be surprising

**Comment by phlptp** [comment]
Deal with these one by one

#  Metres

I think I missed a capital letter in the check for this spelling, will be fixed

#  cars/hour/meter^2
interpreted as centi- ares =m^2 
a little odd but I would consider it correct

#  degrees C 
 `0.0174532925199432955s*A*rad` | to be fixed right now reading as degrees (angle) * coulomb

# cm+cm 

  + is usually non-sensical in terms of units so interpreted as * non numeric context.  Could consider alternate interpretations if the units have the same base then it could be additive 

# kM
kmol/L correct, but may be surprising (M= molarity = mol/L, so this seems correct) correct, but may be surprising (M= molarity = mol/L, so this seems correct)

# Others
Still exploring these
| gramm | 6.47989100000000217e-23g*m | this would be a typo, or German spelling
| kilogramm | 6.47989100000000188e-20g*m | ?


| fps | ft/s | not sure if this is the most common interpretation? Isn't frames per second more common?


| inchy | 4830819306288062m^3/[c] | would expect an error instead of bad parsing
| fln_oz | 9.7132811577355196e-08g*cd/m^2 | would expect an error instead of bad parsing

**Comment by phlptp** [comment]
`inchy`  my first thought was that this should read inch*year.  Whether even that would be good is probably questionable.
What seems to be happening is that it interprets it as inch*chain*year  which oddly dividing by the speed of light ends up producing the most compact unit string since chain isn't one of the standard output strings.

**Comment by phlptp** [comment]
fln_oz  = foot-lambert newton ounce

I think I am going to disable the partitioning when there is an underscore, and be a little less permissive.  That will come in the next PR.

**Comment by phlptp** [comment]
This was pretty interesting to work through.  
There is now a defaultflag property that can be set and gets used if no flags are entered in the api call. A minimum partition size can be specified as part of those flags.  This allows better control of the conversion process for programs using the conversion.

**Comment by SimonHeybrock** [comment]
Thanks! Do you plan to make a release soon?

**Comment by phlptp** [comment]
I hope to make a new release with these changes within this coming week.
